name: idrel
version: "2.45"
license: "GPL-2.0-or-later"
date: 2023-02-09
description: |
    Identities among relations

authors:
    - name: Anne Heyworth
    - name: Chris Wensley
      url: https://github.com/cdwensley

maintainers:
    - name: Chris Wensley
      url: https://github.com/cdwensley

GAP: ">=4.11.1"

www: https://gap-packages.github.io/idrel/
readme: README.md
packageinfo: https://gap-packages.github.io/idrel/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/idrel/releases/download/v2.45/idrel-2.45.tar.gz

abstract: |
    IdRel is a package for computing the identities among relations of a group presentation using rewriting, logged rewriting, monoid polynomials, module polynomials and Y-sequences.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    logged rewriting, identities among relations, Y-sequences.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>HW23</span>]   <b class='BibAuthor'>Heyworth, A. and Wensley, C.</b>,
     <i class='BibTitle'>idrel, Identities among relations,
             Version 2.45</i>
     (<span class='BibYear'>2023</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/idrel/">https://gap-packages.github.io/idrel/</a></span>.
    </p>
    

bibtex: |
    @misc{ idrel2.45,
      author =           {Heyworth, A. and Wensley, C.},
      title =            {{idrel}, Identities among relations, {V}ersion 2.45},
      month =            {Feb},
      year =             {2023},
      note =             {Refereed GAP package},
      howpublished =     {\href          {https://gap-packages.github.io/idrel/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{idrel/}}},
      keywords =         {logged    rewriting;   identities   among   relations;
                          Y-sequences},
      printedkey =       {HW23}
    }

