name: idrel
version: "2.44"
license: "GPL-2.0-or-later"
date: 2022-06-04
description: |
    Identities among relations

authors:
    - name: Anne Heyworth
    - name: Chris Wensley
      url: https://github.com/cdwensley

maintainers:
    - name: Chris Wensley
      url: https://github.com/cdwensley

GAP: ">=4.11.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.6.2"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

suggested-pkgs:
    - name: "AutoDoc"
      version: ">= 2018.09.20"
      url: "https://gap-packages.github.io/AutoDoc"

www: https://gap-packages.github.io/idrel/
readme: README.md
packageinfo: https://gap-packages.github.io/idrel/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/idrel/releases/download/v2.44/idrel-2.44.tar.gz

abstract: |
    IdRel is a package for computing the identities among relations of a group presentation using rewriting, logged rewriting, monoid polynomials, module polynomials and Y-sequences.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    logged rewriting, identities among relations, Y-sequences.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>HW22</span>]   <b class='BibAuthor'>Heyworth, A. and Wensley, C.</b>,
     <i class='BibTitle'>idrel, Identities among relations,
             Version 2.44</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/idrel/">https://gap-packages.github.io/idrel/</a></span>.
    </p>
    

bibtex: |
    @misc{ idrel2.44,
      author =           {Heyworth, A. and Wensley, C.},
      title =            {{idrel}, Identities among relations, {V}ersion 2.44},
      month =            {Jun},
      year =             {2022},
      note =             {Refereed GAP package},
      howpublished =     {\href          {https://gap-packages.github.io/idrel/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{idrel/}}},
      keywords =         {logged    rewriting;   identities   among   relations;
                          Y-sequences},
      printedkey =       {HW22}
    }

