name: idrel
version: 2.33
date: 18/10/2016
description: Identities among relations

authors:
    - name: Anne Heyworth
    - name: Christopher D. Wensley
      url: http://pages.bangor.ac.uk/~mas023/

maintainers:
    - name: Christopher D. Wensley
      url: http://pages.bangor.ac.uk/~mas023/

GAP: ">=4.7"

needed-pkgs:
    - name: "xmod"
      version: ">= 2.56"
      url: "http://gap-packages.github.io/xmod/"
    - name: "GAPDoc"
      version: ">= 1.5.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/idrel/
readme: https://gap-packages.github.io/idrel/README
packageinfo: https://gap-packages.github.io/idrel/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/idrel/releases/download/v2.33/idrel-2.33.tar.gz

abstract: IdRel is a package for computing the identities among relations of a group presentation using rewriting, logged rewriting, monoid polynomials, module polynomials and Y-sequences.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
