name: idrel
version: "2.49"
license: "GPL-2.0-or-later"
date: 2025-10-02
description: |
    Identities among relations

authors:
    - name: Anne Heyworth
    - name: Chris Wensley
      url: https://github.com/cdwensley

maintainers:
    - name: Chris Wensley
      url: https://github.com/cdwensley

GAP: ">=4.11.1"

www: https://gap-packages.github.io/idrel/
readme: README.md
packageinfo: https://gap-packages.github.io/idrel/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/idrel/releases/download/v2.49/idrel-2.49.tar.gz

abstract: |
    <span class="pkgname">IdRel</span> is a package for computing the identities among relations of a group presentation using rewriting, logged rewriting, monoid polynomials, module polynomials and Y-sequences.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    logged rewriting, identities among relations, Y-sequences.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>HW25</span>]   <b class='BibAuthor'>Heyworth, A. and Wensley, C.</b>,
     <i class='BibTitle'>idrel, Identities among relations,
             Version 2.49</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/idrel/">https://gap-packages.github.io/idrel/</a></span>.
    </p>
    

bibtex: |
    @misc{ idrel,
      author =           {Heyworth, A. and Wensley, C.},
      title =            {{idrel}, {Identities among relations}, {V}ersion 2.49},
      month =            {Oct},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href          {https://gap-packages.github.io/idrel/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{idrel/}}},
      keywords =         {logged    rewriting;   identities   among   relations;
                          Y\texttt{\symbol{45}}sequences},
      printedkey =       {HW25}
    }

